output: ./data/raw

index:
  store: ./data/store
  sonic:
    host: sonic
    port: 1491
    password: password

modules:
  - path: modules/akim
    enable: true
    index:
      enable: false
      files: [pdf]
  - path: modules/debug-pro
    enable: true
    index:
      enable: true
      files: [pdf]
  - path: modules/epidocs-past-exams
    enable: true
    index:
      enable: false
      files: [pdf]
  - path: modules/intra
    enable: false
    options:
      LOGIN: your.login
      PASSWORD: your_cri_password
    index:
      enable: false
      files: [pdf]
  - path: modules/lse.epita.fr
    enable: false
    index:
      enable: true
      files: [pdf]
  - path: modules/mastercorp.epita.eu
    enable: false
    index:
      enable: true
      files: [pdf]
  - path: modules/algo.infoprepa.epita.fr
    enable: false