version: "2.0"
services:
  docconv:
    image: docconv
    # build:
    #   context: ./docker
    #   dockerfile: Dockerfile.docconv
    ports:
      - "8888:8888"
  sonic:
    image: valeriansaliou/sonic:v1.3.2
    ports:
      - 1491:1491
    volumes:
      - ./sonic/config.cfg:/etc/sonic.cfg
      - ./sonic:/sonic
