on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: [self-hosted]
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./...
  build_modules:
    runs-on: [self-hosted]
    name: Build modules
    steps:
      - uses: actions/checkout@v2
      - run: for m in $(ls modules); do docker build -t epitar-module-$m-$(date +%s) modules/$m; done